feat: Assign members
blomstra/flarum-ext-trello pull request #13
Opened 2021-12-13 13:20 UTC by bkintanar

#11 must be merged first.

See: [Orion: Trello: Assign members](https://trello.com/c/TdCm5yRr)

2021-12-13 13:23 UTC, davwheat approved these changes

2021-12-13 13:23 UTC, davwheat commented on src/Controllers/DeleteBoardController.php
> +        if ($shortLink == $defaultBoardId) {
```suggestion
        if ($shortLink === $defaultBoardId) {
```

2021-12-13 13:34 UTC, imorland requested changes
Looking generally ok. One change please so far.

Am heading off for lunch now, will test locally after

2021-12-13 13:34 UTC, imorland commented on src/Listener/SaveTrelloIdToDatabase.php
> +        $client = resolve(Client::class);
No need to resolve the client again here, it's available already `$this->client`

2021-12-14 14:34 UTC, imorland approved these changes

2021-12-14 14:35 UTC, merged