feat: Remember last used trello lane
blomstra/flarum-ext-trello pull request #2
Opened 2021-11-19 14:51 UTC by bkintanar

See: https://trello.com/c/aEzpUohp

2021-11-19 15:08 UTC, imorland requested changes

2021-11-19 15:08 UTC, imorland commented on extend.php
> +        ->serializeToForum('trelloLastUsedLaneId', 'blomstra-trello.last_used_lane_id', 'strval'),
I'm actually thinking we should hide all of this from the api, unless the user has Trello permission. 

Can you move these to https://github.com/blomstra/flarum-ext-trello/blob/master/src/TrelloAttributes.php please and remove the `Extend\Settings`

2021-11-19 15:08 UTC, imorland commented on src/Listener/SaveTrelloIdToDatabase.php
> +        $this->settings->set('blomstra-trello.last_used_lane_id', $lane);
Rather than setting this each time, perhaps get the current value of the key and only set if it's different?

2021-11-21 14:34 UTC, davwheat approved these changes

2021-11-22 08:14 UTC, imorland approved these changes

2021-11-22 08:15 UTC, merged