feat: Suffix post username to Trello title
blomstra/flarum-ext-trello pull request #4
Opened 2021-11-19 16:17 UTC by bkintanar

See: [Orion: Trello: Suffix post username to Trello title](https://trello.com/c/3A1jwQXz)

2021-11-21 14:35 UTC, davwheat approved these changes

2021-11-21 14:42 UTC, davwheat requested changes
I just noticed these things, actually. I think we try not to use the `forum` locale namespace except for things that will appear on the forum itself.

I think `lib` is a better choice as this translation is only used on the backend.

2021-11-21 14:42 UTC, davwheat commented on locale/en.yml
> +    original_post: Original post
```suggestion
  lib:
    original_post: Original post
```

2021-11-21 14:42 UTC, davwheat commented on src/Listener/SaveTrelloIdToDatabase.php
> +        $originalPost = $this->translator->trans('blomstra-trello.forum.original_post');
```suggestion
        $originalPost = $this->translator->trans('blomstra-trello.lib.original_post');
```

2021-11-21 14:48 UTC, davwheat approved these changes

2021-11-22 08:03 UTC, imorland approved these changes

2021-11-22 08:06 UTC, merged